version: '3.7'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  database: